name: Toggle branch protection

on:
  schedule:
    - cron: '0 6 * * *'  # Corre todos los días a las 6:00 UTC (12:00 AM en Costa Rica)
  workflow_dispatch:

jobs:
  toggle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Comprobar si hoy es fecha de bloqueo
      id: datecheck
      run: |
        TODAY=$(date +'%Y-%m-%d')
        TARGET="2025-06-03"  # Cambiar fecha de bloqueo según sea necesario
        if [ "$TODAY" = "$TARGET" ]; then
          echo "block=true" >> $GITHUB_OUTPUT
        else
          echo "block=false" >> $GITHUB_OUTPUT
        fi

    - name: Bloquear ramas (main y develop)
      if: steps.datecheck.outputs.block == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.MY_PAT }}
        script: |
          const branches = ['main', 'develop'];
          for (const branch of branches) {
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              enforce_admins: true,
              required_status_checks: null,
              required_pull_request_reviews: null,
              restrictions: {
                users: [],
                teams: []
              }
            });
          }

    - name: Restaurar protección normal (main y develop)
      if: steps.datecheck.outputs.block == 'false'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.MY_PAT }}
        script: |
          const branches = ['main', 'develop'];
          for (const branch of branches) {
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              enforce_admins: false,
              required_status_checks: {
                strict: true,
                contexts: ['ci-build']
              },
              required_pull_request_reviews: null,
              restrictions: {
                users: [],
                teams: []
              }
            });
          }
